### ISSUE TITLE
What is in the blank channels in channels list?

### ISSUE THREAD

**Issue by tessbrodie** [guiwitz/napari-steinpose#1]
Thanks for your great tool and we are really enjoying how much it speeds up our cell segmentation.  We had the issue that not all the channels acquired were given names in the acquisition template, so the channel was acquired, but no protein target or metal name was given.  We do not know of any way to edit the channel names in an MCD file, but we saw that there are unnamed boxes to tick under the channel names and we looked in there to see if our target of interest was there.  We could not find it and were wondering if you could let us know what is in those blank spaces with no names, but boxes under the Channels tab?  
Thanks so much for your time and support,
Best,
Tess

**Comment by guiwitz** [comment]
Thanks for reporting this issue. Normally, I rename the "empty channels" with some generic name (as is done in the layers on the left of the viewer). It can be that I didn't copy these generic names to the channels tab and so they appear empty. I will look into this this week.

**Comment by guiwitz** [comment]
I had a look at this @tessbrodie. I'm indeed not renaming the empty channels at the moment. There are two possible solutions. First we can just fill the empty channels names with numerical indices (1,2,3, ...) as is done by Steinbock. Alternatively, we could use the metal names (which are of course all different) as a "fill-in": we could just use the metal name if there's no target name or we could create a combined name as ```target - metal```. The latter is maybe clearer as we wouldn't mix-up target and metal names. We would just have e.g. cases with ```CD19 - Nd142``` when we have both infos and cases e.g. with ``` - Nd143``` if the target is missing. Let me know what you prefer.

**Comment by tessbrodie** [comment]
Dear Guiwitz/Napari-Steinpose,
Thanks so much for looking into this and it would be great if you could put
the target when they are present and just the metal when no target is
present. I see your point about putting both target and metal or just metal
when no target is present, but I am worried that could become annoying in
the Steinbock export if the channels are all named like that for the data
analysis.
Thanks for your time and support,
Best,
Tess

**Comment by guiwitz** [comment]
Ok I added the feature as requested in commit [cf32672](https://github.com/guiwitz/napari-steinpose/commit/cf32672c5a8dfba390628a1010a684356fc2832d). Channels whose target is not defined are named with the metal.

**Comment by tessbrodie** [comment]
That's great, thanks so much!
